- .codeclimate.yml
I didn't include [golint](https://docs.codeclimate.com/docs/golint) because the results seemed overly strict, but open to enabling it if y'all like.
> add Code Climate config

- ci/create-db.yml
- ci/update-broker.yml
The `governmentpaas/cf-cli` image recently switched to alpine, which means we don't have `bash` anymore. Switching images is quicker than switching scripts to `sh`.
@dlapiduz
> Use omnibus docker image for concourse tasks.

- README.md
README was misleading about the `path` variable and didn't mention `insecure_origin`
> Remove path slash, add note about insecure_origin

- ci/acceptance-tests.sh
- ci/credentials.example.yml
- ci/pipeline.yml
Because apparently cloudfront can take over an hour to deprovision.
> Bump and expose cdn timeout.

- catalog.json
To keep consistent names and documentation for services on the dashboard and other services.
This service does not have an icon.
Part of this story: https://github.com/18F/cg-dashboard/issues/857
> Update service metadata

- catalog.json
This is a followup on https://github.com/18F/cf-cdn-service-broker/pull/56 with a few edits to hopefully explain the service a bit more clearly. This goes along with https://github.com/18F/cg-site/pull/684 which updates the relevant docs page as well.
I'm not entirely sure these are the right edits for this metadata, since I don't know which field matches which part of the page, so feel free to correct/comment.
cc @msecret @thisisdano
> Adjust metadata description

- manifest-base.yml
I think this should be enough:
```
± cf app cdn-broker
Showing health and status for app cdn-broker in org cloud-gov / space services as joshua.carp@gsa.gov...
OK
requested state: started
instances: 1/1
usage: 512M x 1 instances
urls: cdn-broker.fr.cloud.gov
last uploaded: Fri Jan 27 22:27:42 UTC 2017
stack: cflinuxfs2
buildpack: go_buildpack
state     since                    cpu    memory          disk          details
#0   running   2017-01-27 05:28:55 PM   0.0%   15.9M of 512M   87.3M of 1G
```
> Set reasonable memory limit.

- cmd/cdn-cron/main.go
- models/mocks/RouteManagerIface.go
- models/models.go
- models/models_test.go
- utils/cloudfront.go
- utils/iam.go
This PR changes the CDN broker so that the process of deleting old certificates is not linked to the renewal process.  The broker now uses the service instance id and the expiration date of the certificate to generate a unique name when uploading a cert rather than the `-new` suffix.
A separate process prunes old certificates, removing any certificates under the configured `IamPathPrefix` that are not associated with a distribution and are older than 24 hours.  The time check is intended to prevent accidental pruning of newly uploaded certificates that haven't been associated with a distribution yet.
When testing this in staging, it correctly identified and removed an existing orphaned cert:
2017-04-06T18:00:01.68-0700 [APP/PROC/WEB/0]ERR …
> Decouple deleting old certificates from the renewal process

- utils/certs.go
For debugging intermittent errors with the http challenge precheck that mysteriously resolve on app restart. cc @LinuxBozo
> Show expected and observed tokens on mismatch.

- models/models.go
Prior to this change, we create cloudfront distributions before acme challenges.
If creating acme challenges fails, we're left with an orphaned cloudfront
distribution that the broker isn't aware of. This patch gets the acme challenges
first to avoid this confusing state.
> Prevent failed challenges from creating orphaned distributions.

- utils/certs.go
It looks like our http challenge pre-check can cache dns lookups. Specifically, if a user migrates an existing domain to this broker, the pre-check seems to get stuck on the previous address long after dns has been updated, and can only be fixed by restarting the broker. For reasons I frankly don't understand, creating the http client once per pre-check instead of at the module level fixes this, which I verified by creating a few stuck instances before deploying this change and a few successful instances afterwards.
This should resolve an issue that @wslack ran into a few times such that moving a domain from the east client elb for 18f.gov to govcloud would get stuck and require talking to support.
> Debug potential dns caching.

- cmd/cdn-broker/main.go
- cmd/cdn-broker/main_test.go
- glide.lock
- healthchecks/cloudfoundry.go
- healthchecks/cloudfront.go
- healthchecks/healthchecks.go
- healthchecks/letsencrypt.go
- healthchecks/postgresql.go
- healthchecks/s3.go
- vendor/github.com/cloudfoundry-community/go-cfclient/apps.go
- vendor/github.com/cloudfoundry-community/go-cfclient/client.go
- vendor/github.com/cloudfoundry-community/go-cfclient/client_test.go
- vendor/github.com/cloudfoundry-community/go-cfclient/spaces.go
Add a simple healthcheck endpoint. We deploy the CDN broker on its own VM and access it via an ELB. This endpoint is used by the ELB to check if the app is running. It should not be protected by the basic auth.
Also, the cfclient library is updated to avoid annoying crashes.
* `cd cdm/cdn-broker && go test`
* Deploy
* Access `/healthcheck`, it should return `HTTP 200 OK`
> Add healthcheck endpoint

- ci/acceptance-tests.sh
This fixes what I believe is a [race condition](https://ci.fr.cloud.gov/teams/main/pipelines/deploy-cdn-broker/jobs/acceptance-tests-production/builds/28) between the DNS and HTTP challenge tests when they are run in parallel.
This condition can occur when the tests are only seconds behind each other, which can cause the test app to be in a staging state when the second app attempts a `cf push`.  This will cause a [VCAP::CloudController::BuildCreate::StagingInProgress](https://github.com/cloudfoundry/cloud_controller_ng/blob/faa8a762a0ac84383a7a6d1735a72d9cc3616413/spec/unit/actions/build_create_spec.rb#L257-L265) error and fail the test.
> fix race condition in acc tests

- utils/cloudfront.go
We should drop tls 1.0 (and probably 1.1) soon, but need to look into usage and write customer comms first. For now, restore tls 1.0, but drop support for DES-CBC3-SHA by using tlsv1_2016 instead of the original tlsv1.
h/t @konklone
> Restore TLS 1 and deprecate DES cipher.

- utils/cloudfront.go
Fixes this:
```
1 validation error detected: Value '[TLSv1.0, TLSv1.1, TLSv1.2]' at 'distributionConfigWithTags.distributionConfig.origins.items.1.member.customOriginConfig.originSslProtocols.items' failed to satisfy constraint: Member must satisfy constraint: [Member must satisfy enum value set: [SSLv3, TLSv1, TLSv1.1, TLSv1.2]]
```
😅
> Revert tls config again.

- utils/cloudfront.go
CloudFront now requires setting origin read timeout on updates.
> Set origin read timeout to default.

- utils/cloudfront.go
Merge at the end of the month. We'll also need to update existing cloudfront instances.
> [WIP] Drop tls 1.0 and 1.1.

- ci/acceptance-tests.sh
- ci/pipeline.yml
So that we can test staging against the staging let's encrypt service.
> Optionally set cacert during acceptance tests.

- models/models.go
- utils/cloudfront.go
Myself and @46bit took #116 and applied it to GDS's fork alphagov/paas-cdn-broker but @46bit found that `Update` was broken for the same reason as `Create` pre-fix.
This PR is the code-change in #116, plus an additional commit which uses the old domains when updating Cloudfront in `Update`, and relies on `deployCertificate` to do the actual certificate and CNAME changes.
Please let us know if we need to sign a CLA, alternatively feel free to ignore/close this PR.
[Context](https://github.com/alphagov/paas-cdn-broker/pull/13)
> Update cnames after getting certs (for Update and Create)

- ci/pipeline.yml
More fallout from CloudFront changing their API. HTTP01 tests no longer work because CloudFront responds to all requests with mismatched Host headers by sending a 403.
This only tears out the test so we can ship what we have - there's still work to be done to update docs and cli output to make it clear we don't support HTTP01
> Drop http-01 tests

- broker/broker.go
- remove the assertion that the number of instructions is the same as the number of domains.
This check is invalid, for instance, when adding a new domain to an instance with an already-verified domain.
None
> remove check on length of instructions vs number of domains

- ci/acceptance-tests.sh
- pause for 5 seconds between creating the domain and creating the service instance that needs it
none
> pause for a little bit between creating domain and service instance

- broker/broker.go
- models/models.go
- Add a path for failed updates. Currently, we assume a service instance is either changing or successful, and have no way of reporting that it's failed
- Set service instance to failed when a failure happens while updating cloudfront after getting a certificate. this fixes 18F/cg-product#1083 
None - this just cleans up error handling
> add error logic for failed CloudFront update

- models/models.go
- the `Settings` struct contains AWS key information: https://github.com/cloud-gov/cf-cdn-service-broker/blob/42e47a9371fd070b37f3d6575bd87d92b473f1f5/config/config.go#L20-L22, so removing the line that it includes it in logs
This change removes code that was logging sensitive information to the output
> remove log of sensitive data
