cloud-gov/cf-cdn-service-broker

.travis.yml
README.md

https://docs.travis-ci.com/user/languages/go

add Travis CI config

---

README.md

Some formatting fixes, and including some missing instructions.

clean up the README

---

broker/broker.go
broker/broker_test.go
models/models.go

Represent route state using enum.

---

ci/pipeline.yml
ci/run_tests.sh
ci/run_tests.yml

Run tests in concourse before deploy.

---

README.md
models/models.go
utils/certs.go
utils/cloudfront.go

The idea here is to allow users to pass a comma delimited string rather than just one domain.

[WIP] Support Multiple domains

---

models/models.go

Save certificate payload without private key.

---

models/models.go

Compare hosts across domain and distribution.

---

ci/pipeline.yml

Replace hard-coded url with ATC_EXTERNAL_URL.

---

README.md
broker/broker.go
broker/broker_test.go
models/models.go
utils/cloudfront.go

This would allow us to support Federalist urls...

Add an option to pass in a path parameter to the distribution

---

ci/pipeline.yml
cmd/cdn-cron/main.go
config/config.go
manifest-broker.yml
manifest-cron.yml

Fix manifest

---

broker/broker.go
broker/broker_test.go

Add more informative messages to last operation.

---

cmd/cdn-cron/main.go
models/models.go

Log renew attempts.

---

README.md
broker/broker.go

For unsticking expired service instances.

Dummy update

---

broker/broker.go
broker/broker_test.go
models/models.go
utils/cloudfront.go

http://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html
@dlapiduz

Tag distributions with service info.

---

broker/broker.go
broker/broker_last_operation_test.go
broker/broker_provision_test.go
models/mocks/RouteManagerIface.go
models/models.go

If the state is change for route, we need to pass by pointer

Pass by pointer for "Update" to ensure that internal state

---

broker/broker.go
broker/broker_last_operation_test.go
broker/broker_update_test.go
catalog.json
models/mocks/RouteManagerIface.go
models/models.go
utils/cloudfront.go

Builds on #44. Closes #43. Pairing with @jcscottiii.

Allow user to update CDN options

---

ci/acceptance-tests.sh
ci/acceptance-tests.yml
ci/credentials.example.yml
ci/pipeline.yml

Need help from @dlapiduz to delegate a domain to the hosted zone in the right aws account.

Add acceptance test.

---

ci/pipeline.yml

Fix typo on production deploy.

---

utils/cloudfront.go

use instance id for origin id

---

README.md

I was reading your readme and noticed few small issues with formatting, which spoil otherwise well written readme, so I decided to fix them...

Fix few typos and formatting in README

---

utils/cloudfront.go

change all instances of s3 origin id :/

---

models/models.go

Set userdata email address.

---

cmd/cdn-broker/main.go
cmd/cdn-cron/main.go

Run auto-migrate on cron init.

---

broker/broker.go
broker/broker_last_operation_test.go
cmd/cdn-broker/main.go
cmd/cdn-cron/main.go
models/mocks/RouteManagerIface.go
models/models.go
models/models_test.go

TODO: Make sure unique constraint on `UserData` email gets dropped from postgres, and point all existing `Route` rows to the existing `UserData`.

[WIP] Provision an acme user per service instance.

---

models/models.go

First commit: WDYT about doing something like this so we don't generate authzs for CDN-routes instances that aren't deleted but are no longer in use?
Second commit: Fix issue where any site that has renewed in the past will get stuck in a renewal loop when it's time for the 2nd or greater renewal.
Using federalist as an example:
```
> select id,expires from certificates where domain='federalist.18f.gov';
id  |        expires         
-----+------------------------
127 | 2017-07-20 14:31:00+00
202 | 2017-10-17 05:31:00+00
(2 rows)
```
```
> select domain_external,expires from routes join certificates on routes.id = certificates.route_id where state='provisioned' and expires < now() + interval '30 days';
-------------------------------------------------------------------------+-------------- …
```

Check route is still active before renewing domain

---

ci/acceptance-tests.sh

Make tests more robust to handle changes in cf cli.

Use API instead of CLI for more robust smoke tests.

---

utils/cloudfront.go

Fix typo on ssl protocol quantity.

---

models/models.go
utils/cloudfront.go

CloudFront recently changed their requirements so we now need to upload a certificate whenever setting a distribution cname. This PR delays setting the cname until we have a certificate.
This PR offers the following advantages over 18F/cf-cdn-service-broker#115:
- no doc changes required
- continued support for HTTP-01 cert challenges
- no database schema changes

Update cnames after getting certs

---

models/models.go

Added some verbosity to the route manager provisioning stage to help with debugging.
Signed-off-by: Mike Lloyd <mike.lloyd@gsa.gov>

added error logging for provisioning.

---

models/models.go

just adding more logging context to assist with debugging.
Signed-off-by: Mike Lloyd <mike.lloyd@gsa.gov>

added more logging sessions.

---

ci/pipeline.yml

Resolves error when attempting to set pipeline with a yaml file that contains anchors by moving anchor to the beginning of the file. Also fixes two missing quotation marks.

Remove anchors

---

.gitignore
ci/pipeline.yml

- stop registering the broker
- stop running smoke tests
None

No more new service instances

---

ci/pipeline.yml

- drop references to acceptance tests, since we deleted them
None

don't reference removed acceptance tests

---

manifest-base.yml

- use a supported buildpack version
None

use supported buildpack

---

manifest-base.yml

- bump goversion so we can restage
None

bump goversion so we can restage

---

manifest-base.yml

-Updated manifest for go v1.20
-
-
There are no security considerations for this change.

Updated manifest for go v1.20

---

ci/pipeline.yml

- New CF resources + other hardened
This improves stuff by using harden resources

New CF resources + other hardened

---

manifest-base.yml

- Fixing old go buildpack
-
-
none

go version will not work in pipeline

---

ci/acceptance-tests.yml
ci/create-db.yml
ci/run-tests.yml

- Updating scripts to use hardened containers
Using hardened containers

update scripts to use hardened containers
